---

site_name: JEODPP - Condor Tutorial

theme:
  name: material

nav:
    - 'Home': index.md
    - 'User Guide':
        - 'Set things up': '00_set_things_up.md'
        - 'The first job': '01_the_first_job.md'
        - 'The second job': '02_the_second_job.md'


markdown_extensions:
  - 'admonition'
  - 'codehilite'
  - toc:
      permalink: true
