---

site_name: JEO-Batch Tutorial (for first time users!)

theme:
  name: material

nav:
    - 'Home': index.md
    - 'User Guide':
        - 'Set things up': '00_set_things_up.md'
        - 'The first job': '01_the_first_job.md'
        - 'When things go wrong': '02_when_things_go_wrong.md'


markdown_extensions:
  - 'admonition'
  - 'codehilite'
  - toc:
      permalink: true
